server:
  port: 8088
spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/yeb?serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    # 最小连接池数量
    minIdle: 10
    # 最大连接池数量
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 配置一个连接在池中最大生存的时间，单位是毫秒
    maxEvictableIdleTimeMillis: 900000
    # 配置检测连接是否有效
    validationQuery: SELECT 1 FROM DUAL
    #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    testWhileIdle: true
    #配置从连接池获取连接时，是否检查连接有效性，true每次都检查；false不检查。做了这个配置会降低性能。
    testOnBorrow: false
    #配置向连接池归还连接时，是否检查连接有效性，true每次都检查；false不检查。做了这个配置会降低性能。
    testOnReturn: false
  #redis配置
  redis:
    timeout: 10000ms
    #服务器端口
    host: 127.0.0.1
    #服务器端口
    port: 6379
    #数据库
    database: 0
    #密码
    #password: 123456
    lettuce:
      pool:
        #最大连接数
        max-active: 1024
        #最大连接阻塞等待时间
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        #最小空闲连接
        min-idle: 5
  #rabbitmq配置
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672
    #消息确认回调
    publisher-confirm-type: correlated
    #消息失败回调
    publisher-returns: true
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: cn.yfxu.server.pojo
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.yfxu.server.mapper: debug

#jwt:
#  #jwt存储的请求头
#  tokenHeader: Authorization
#  #jwt 加解密使用的密钥
#  secret: yeb-secret
#  #jwt的超期限时间(S)
#  expiration: 604800
#  #jwt负载中拿到的开头
#  tokenHead: Bearer
